### ISSUE TITLE
"Defs_OnDemand" should test the existence of a Def.

### ISSUE THREAD

**Issue by jinlan** [notfood/RimWorld-SeedsPlease#17]
Mod "Syrchalis Blueberries" removes many defs from VGP. When I have both Syr and VGP, I will get a "def not found" error, because those defs are removed by Syr.
Would you please check the existence of a Def before run a auto-seed-creation?

**Comment by notfood** [comment]
That's not part of auto seed creation. Those Defs found on the Defs_OnDemand folder are merely more XML loaded whenever the mod exists.

This is a visual bug, only people with developer console enabled will see it and it doesn't affect gameplay as it can be ignored.

The solution would be to use Patches to remove the seeds in the xml that don't belong if Syrchalis Blueberries is loaded. A mere copy paste of their patch that instead of the plants, it has the seeds removed.

Alternatively, add aditional logic to Patches/LoadOnDemand_Addons.xml so it loads a different VGP if Syrchalis Blueberries is loaded.

Very low priority in my list, feel free to contribute such patch.
